// SPDX-License-Identifier: MIT
//
// RuntimeStubs.cs
// ===============
// NativeAOT (and the C# compiler) sometimes emit calls to a handful of CRT
// helpers — even when /NODEFAULTLIB is in effect. Under a UEFI environment
// there is no C runtime, so we provide minimal replacements as unmanaged
// exported symbols. These are linked into every EDK2Net application that
// references this library.
//
// References for which symbols may appear:
//   * memcpy, memset, memmove, memcmp  — generated by the JIT/IL2CPP/AOT for
//     block-copies and struct moves.
//   * __chkstk (x64) — emitted by the prolog of functions whose stack frame
//     exceeds one page. UEFI page tables map enough stack that we can no-op it.
//
// The implementations are intentionally byte-by-byte and unoptimized. They
// will be hit only on rarely-used paths; for hot paths use the UEFI
// BootServices CopyMem / SetMem instead.

namespace EDK2Net.Runtime;

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public static unsafe class RuntimeStubs
{
    [UnmanagedCallersOnly(EntryPoint = "memcpy")]
    public static void* MemCpy(void* dest, void* src, nuint count)
    {
        byte* d = (byte*)dest;
        byte* s = (byte*)src;
        for (nuint i = 0; i < count; i++) d[i] = s[i];
        return dest;
    }

    [UnmanagedCallersOnly(EntryPoint = "memmove")]
    public static void* MemMove(void* dest, void* src, nuint count)
    {
        byte* d = (byte*)dest;
        byte* s = (byte*)src;
        if (d == s || count == 0) return dest;
        if (d < s)
        {
            for (nuint i = 0; i < count; i++) d[i] = s[i];
        }
        else
        {
            for (nuint i = count; i > 0; i--) d[i - 1] = s[i - 1];
        }
        return dest;
    }

    [UnmanagedCallersOnly(EntryPoint = "memset")]
    public static void* MemSet(void* dest, int value, nuint count)
    {
        byte* d = (byte*)dest;
        byte  v = (byte)value;
        for (nuint i = 0; i < count; i++) d[i] = v;
        return dest;
    }

    [UnmanagedCallersOnly(EntryPoint = "memcmp")]
    public static int MemCmp(void* a, void* b, nuint count)
    {
        byte* pa = (byte*)a;
        byte* pb = (byte*)b;
        for (nuint i = 0; i < count; i++)
        {
            int diff = pa[i] - pb[i];
            if (diff != 0) return diff;
        }
        return 0;
    }

    // __chkstk probes the stack one page at a time so the OS can grow it.
    // Under UEFI the boot stack is fully mapped, so a no-op is safe.
    // The MSVC calling convention for __chkstk passes the size in RAX and
    // does not perturb any other registers; from C# we just return.
    [UnmanagedCallersOnly(EntryPoint = "__chkstk")]
    public static void ChkStk() { }

    // Some toolchains expect _fltused to be present whenever floating point
    // is used. Export it as a zero data symbol so the linker is satisfied.
    [UnmanagedCallersOnly(EntryPoint = "_fltused")]
    public static int FltUsed() => 0;

    // Force a reference so the linker keeps these exports in any consuming
    // application even if the optimizer thinks they are unused.
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void KeepAlive()
    {
        // Cast the function pointers to void* to discard the result.
        _ = (void*)(delegate* unmanaged<void*, void*, nuint, void*>)&MemCpy;
        _ = (void*)(delegate* unmanaged<void*, void*, nuint, void*>)&MemMove;
        _ = (void*)(delegate* unmanaged<void*, int, nuint, void*>)&MemSet;
        _ = (void*)(delegate* unmanaged<void*, void*, nuint, int>)&MemCmp;
        _ = (void*)(delegate* unmanaged<void>)&ChkStk;
        _ = (void*)(delegate* unmanaged<int>)&FltUsed;
    }
}
